name: ./configure (s390x)
inputs:
  configurationParameters:
    default: ''
    required: false
  skipSlow:
    default: false
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        ./buildconf --force
        ./configure \
          --enable-option-checking=fatal \
          --prefix=/usr \
          --without-pcre-jit \
          --without-pear \
          --enable-mysqlnd \
          --with-pdo-mysql \
          --with-pdo-pgsql=/usr/bin/pg_config \
          --enable-bcmath \
          --enable-fpm \
          --enable-mbstring \
          --enable-phpdbg \
          --enable-shmop \
          --enable-sockets \
          --enable-sysvmsg \
          --enable-sysvsem \
          --enable-sysvshm \
          --with-zlib \
          --with-curl \
          --with-openssl \
          --enable-pcntl \
          --with-readline \
          ${{ inputs.configurationParameters }} || cat config.log
